### ISSUE TITLE
Bump SBT to 1.x

### ISSUE THREAD

**Issue by adelbertc** [getnelson/nelson#59]
When I tried to do this last time @timperrett said there were some issues with sbt-rig I think?

**Comment by rossabaker** [comment]
I think it was issues with automated publishing, not rig per se. If I
remember correctly, the pgp configuration is only on 0.13 on the Enterprise
Travis that builds it.

I think this might be a problem best solved concurrently with moving off
the enterprise deployment.

On Jan 5, 2018 16:39, "Adelbert Chang" <notifications@github.com> wrote:

When I tried to do this last time @timperrett
<https://github.com/timperrett> said there were some issues with sbt-rig I
think?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/getnelson/nelson/issues/59>, or mute the thread

**Comment by adelbertc** [comment]
Since I assume now builds are no longer going through VZ Enterprise Travis we can bump SBT to the latest and greatest?

**Comment by timperrett** [comment]
Yep, go for it
